language: node_js
node_js: 
  - "stable"


cache:
  dependencies:
    node_modules

script:
  - npm install
  - npm test
  - npm install -g surge
  - npm run build

deploy:
  provider: surge
  cleanup: false
  domain: testdevelopmentbyhaseebahmed.surge.sh 
  project: ./build/

on:
  branch: master